[package]
name = "http-server"
license = "Apache-2.0"
version = "1.0.0"
edition = "2021"

[dependencies]
axum.workspace = true
clap = { workspace = true, features = ["derive", "env", "string"] }
hyper.workspace = true
prometheus-client.workspace = true
tracing.workspace = true
