[package]
name = "grpc-interfaces"
version = "1.0.0"
edition = "2021"

[dependencies]
tonic = "0.9"
prost = "0.11"

[build-dependencies]
tonic-build = "0.9"

[package.metadata.cargo-machete]
ignored = ["prost"]
