[package]
name = "grpc-interfaces"
version = "1.0.0"
edition = "2021"

[dependencies]
tonic.workspace = true
prost.workspace = true

[build-dependencies]
tonic-build.workspace = true

[package.metadata.cargo-machete]
ignored = ["prost"]
