import { BytesLike } from "@ethersproject/bytes";
import fs from "fs";
import response from "./finish_epoch_response.json";

interface OutputValidityProof {
    inputIndexWithinEpoch: number;
    outputIndexWithinInput: number;
    outputHashesRootHash: BytesLike;
    vouchersEpochRootHash: BytesLike;
    noticesEpochRootHash: BytesLike;
    machineStateHash: BytesLike;
    outputHashInOutputHashesSiblings: BytesLike[];
    outputHashesInEpochSiblings: BytesLike[];
}

function setupVoucherProof(positionIndex: number): OutputValidityProof {
    let v = response.proofs[positionIndex].validity;
    let outputHashInOutputHashesSiblingsRawData =
        v.outputHashInOutputHashesSiblings;
    let outputHashesInEpochSiblingsRawData = v.outputHashesInEpochSiblings;
    var outputHashInOutputHashesSiblings: BytesLike[] = [];
    var outputHashesInEpochSiblings: BytesLike[] = [];
    outputHashInOutputHashesSiblingsRawData.forEach((element: any) => {
        outputHashInOutputHashesSiblings.push(element.data);
    });
    outputHashesInEpochSiblingsRawData.forEach((element: any) => {
        outputHashesInEpochSiblings.push(element.data);
    });
    let voucherProof: OutputValidityProof = {
        inputIndexWithinEpoch: Number(v.inputIndexWithinEpoch),
        outputIndexWithinInput: Number(v.outputIndexWithinInput),
        outputHashesRootHash: v.outputHashesRootHash.data,
        vouchersEpochRootHash: v.vouchersEpochRootHash.data,
        noticesEpochRootHash: v.noticesEpochRootHash.data,
        machineStateHash: v.machineStateHash.data,
        outputHashInOutputHashesSiblings: outputHashInOutputHashesSiblings, // siblings should be bottom-up ordered (from the leaf to the root)
        outputHashesInEpochSiblings: outputHashesInEpochSiblings,
    };
    return voucherProof;
}

function setupNoticeProof(positionIndex: number): OutputValidityProof {
    let v = response.proofs[positionIndex].validity;
    let outputHashInOutputHashesSiblingsRawData =
        v.outputHashInOutputHashesSiblings;
    let outputHashesInEpochSiblingsRawData = v.outputHashesInEpochSiblings;
    var outputHashInOutputHashesSiblings: BytesLike[] = [];
    var outputHashesInEpochSiblings: BytesLike[] = [];
    outputHashInOutputHashesSiblingsRawData.forEach((element) => {
        outputHashInOutputHashesSiblings.push(element.data);
    });
    outputHashesInEpochSiblingsRawData.forEach((element) => {
        outputHashesInEpochSiblings.push(element.data);
    });
    let noticeProof: OutputValidityProof = {
        inputIndexWithinEpoch: Number(v.inputIndexWithinEpoch),
        outputIndexWithinInput: Number(v.outputIndexWithinInput),
        outputHashesRootHash: v.outputHashesRootHash.data,
        vouchersEpochRootHash: v.vouchersEpochRootHash.data,
        noticesEpochRootHash: v.noticesEpochRootHash.data,
        machineStateHash: v.machineStateHash.data,
        outputHashInOutputHashesSiblings: outputHashInOutputHashesSiblings,
        outputHashesInEpochSiblings: outputHashesInEpochSiblings,
    };
    return noticeProof;
}

function buildSolCodes(
    noticeProof: OutputValidityProof,
    voucherProof: OutputValidityProof,
    libraryName: string
): string {
    const array1 = noticeProof.outputHashInOutputHashesSiblings;
    const array2 = noticeProof.outputHashesInEpochSiblings;
    const array3 = voucherProof.outputHashInOutputHashesSiblings;
    const array4 = voucherProof.outputHashesInEpochSiblings;
    const lines: string[] = [
        "// SPDX-License-Identifier: UNLICENSED",
        "",
        "pragma solidity ^0.8.8;",
        "",
        "// THIS FILE WAS AUTOMATICALLY GENERATED BY `genProofLibraries.ts`.",
        "",
        'import {OutputValidityProof} from "contracts/library/LibOutputValidation.sol";',
        "",
        `library ${libraryName} {`,
        "    function getNoticeProof() internal pure returns (OutputValidityProof memory) {",
        `        uint256[${array1.length}] memory array1 = [${array1}];`,
        `        uint256[${array2.length}] memory array2 = [${array2}];`,
        `        bytes32[] memory outputHashInOutputHashesSiblings = new bytes32[](${array1.length});`,
        `        bytes32[] memory outputHashesInEpochSiblings = new bytes32[](${array2.length});`,
        `        for (uint256 i; i < ${array1.length}; ++i) { outputHashInOutputHashesSiblings[i] = bytes32(array1[i]); }`,
        `        for (uint256 i; i < ${array2.length}; ++i) { outputHashesInEpochSiblings[i] = bytes32(array2[i]); }`,
        `        return OutputValidityProof({`,
        `            inputIndexWithinEpoch: ${noticeProof.inputIndexWithinEpoch},`,
        `            outputIndexWithinInput: ${noticeProof.outputIndexWithinInput},`,
        `            outputHashesRootHash: ${noticeProof.outputHashesRootHash},`,
        `            vouchersEpochRootHash: ${noticeProof.vouchersEpochRootHash},`,
        `            noticesEpochRootHash: ${noticeProof.noticesEpochRootHash},`,
        `            machineStateHash: ${noticeProof.machineStateHash},`,
        "            outputHashInOutputHashesSiblings: outputHashInOutputHashesSiblings,",
        "            outputHashesInEpochSiblings: outputHashesInEpochSiblings",
        "        });",
        "    }",
        "    function getVoucherProof() internal pure returns (OutputValidityProof memory) {",
        `        uint256[${array3.length}] memory array3 = [${array3}];`,
        `        uint256[${array4.length}] memory array4 = [${array4}];`,
        `        bytes32[] memory outputHashInOutputHashesSiblings = new bytes32[](${array3.length});`,
        `        bytes32[] memory outputHashesInEpochSiblings = new bytes32[](${array4.length});`,
        `        for (uint256 i; i < ${array3.length}; ++i) { outputHashInOutputHashesSiblings[i] = bytes32(array3[i]); }`,
        `        for (uint256 i; i < ${array4.length}; ++i) { outputHashesInEpochSiblings[i] = bytes32(array4[i]); }`,
        `        return OutputValidityProof({`,
        `            inputIndexWithinEpoch: ${voucherProof.inputIndexWithinEpoch},`,
        `            outputIndexWithinInput: ${voucherProof.outputIndexWithinInput},`,
        `            outputHashesRootHash: ${voucherProof.outputHashesRootHash},`,
        `            vouchersEpochRootHash: ${voucherProof.vouchersEpochRootHash},`,
        `            noticesEpochRootHash: ${voucherProof.noticesEpochRootHash},`,
        `            machineStateHash: ${voucherProof.machineStateHash},`,
        "            outputHashInOutputHashesSiblings: outputHashInOutputHashesSiblings,",
        "            outputHashesInEpochSiblings: outputHashesInEpochSiblings",
        "        });",
        "    }",
        "}",
        "",
    ];
    return lines.join("\n");
}

let pairs = response.proofs.length / 2; // need to half because there's a voucher proof and notice proof for each input

// set up proofs
let voucherProofs: OutputValidityProof[] = new Array(pairs);
let noticeProofs: OutputValidityProof[] = new Array(pairs);
for (let i = 0; i < response.proofs.length; i++) {
    let inputIndex = Number(response.proofs[i].inputIndex);
    if (response.proofs[i].outputEnum == "NOTICE") {
        noticeProofs[inputIndex] = setupNoticeProof(i);
    } else {
        voucherProofs[inputIndex] = setupVoucherProof(i);
    }
}

// write to solidity library codes
for (let i = 0; i < pairs; i++) {
    let libraryName = `LibOutputProof${i}`;
    let solidityCode = buildSolCodes(
        noticeProofs[i],
        voucherProofs[i],
        libraryName
    );
    let fileName = `${__dirname}/${libraryName}.sol`;
    fs.writeFile(fileName, solidityCode, (err: any) => {
        if (err) throw err;
        console.log(`File '${fileName}' was generated.`);
    });
}
