[profile.default]
src = 'contracts'
out = 'out'
libs = ['../node_modules', 'lib']
test = 'test/foundry'
cache_path  = 'forge-cache'
solc_version = '0.8.19'
fs_permissions = [
    { access = "read", path = "./test/foundry/dapp/helper/output/"},
    { access = "write", path = "./test/foundry/dapp/helper/input/"}
]

[invariant]
runs = 32
depth = 100
fail_on_revert = true

# See more config options https://book.getfoundry.sh/reference/config.html
