# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Format onchain code
on:
  push:
    paths: 'onchain/**'
jobs:
  onchain:
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: onchain
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v1
        with:
          node-version: "16"
      - run: yarn install
      - run: yarn prettier:rollups
