# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Conventional commit check
on: [push]
jobs:
  commit_messages:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Conventional commit check
        id: conventional_commit_check
        uses: cocogitto/cocogitto-action@v3
        with:
          check-latest-tag-only: true

      - name: Install Lua
        uses: leafo/gh-actions-lua@v10

      - name: Check scopes
        run: |
          lua .github/.check_scopes.lua
