# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Check for unused dependencies
on:
  push:
    paths:
      - '.github/workflows/dependencies.yml'
      - 'offchain/**'
jobs:
  check-offchain-deps:
    runs-on: ubuntu-latest
    env:
      CARGO_REGISTRIES_CARTESI_INDEX: https://github.com/cartesi/crates-index
    defaults:
      run:
        working-directory: offchain

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install cargo-machete
        run: cargo install cargo-machete

      - name: Analyze dependencies
        run: cargo machete .
